# Generated by Django 5.1.1 on 2024-12-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_penerbit', models.CharField(max_length=8)),
                ('nama_penerbit', models.TextField()),
                ('alamat_penerbit', models.TextField()),
                ('kota_penerbit', models.TextField()),
                ('telp_penerbit', models.TextField()),
                ('email_penerbit', models.TextField()),
            ],
        ),
    ]
